//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by variantdesign.rc
//
#define IDCANCEL2                       3
#define IDI_ASM                         1001
#define IDC_LIST_DIMEN                  2000
#define IDD_DIALOG_ALTER                2000
#define IDC_LIST_DIMENSEL               2001
#define IDD_DIALOG_SEARCHER             2001
#define IDC_EDIT_DIMEN                  2002
#define IDC_EDIT_UP                     2003
#define IDD_DIALOG_CHOOSEPRODUCT        2003
#define IDC_EDIT_DOWN                   2004
#define IDD_DIALOG_MODELQUERY           2004
#define IDC_STATIC_DIMEN                2005
#define IDD_DIALOG_PART                 2005
#define IDC_BUTTON_APPLY                2006
#define IDC_BUTTON_GEN                  2007
#define IDD_DIALOG_PARTALTER            2007
#define IDC_BUTTON_SHOW                 2008
#define IDC_BUTTON_GROUPSHOW            2008
#define IDD_DIALOG_ASMQUERY             2008
#define IDC_BUTTON_OK                   2009
#define IDC_LIST1                       2010
#define IDD_DIALOG_UPLOAD               2010
#define IDC_LIST_PRTNDAUDIT             2010
#define IDC_LIST_INFO                   2010
#define IDC_LIST_PDM                    2010
#define IDC_LIST_TASK                   2010
#define IDC_SeriesList                  2010
#define IDC_LIST_DIMENSEL2              2011
#define IDB_BITMAP_ASM                  2011
#define IDB_BITMAP_PART                 2012
#define IDC_LIST_QUERY                  2013
#define IDR_HTML_MAKEUPDLG              2014
#define IDC_EDIT_MAPNUM2                2015
#define IDD_DIALOG_CREATEPRODUCT        2015
#define IDC_EDIT_NAME                   2016
#define IDD_DIALOG2                     2016
#define IDC_EDIT_DIMENNAME              2017
#define IDD_DIALOG_PARTSAVE             2017
#define IDC_EDIT_DIMENVALUE             2018
#define IDC_COMBO_TYPE                  2019
#define IDC_BUTTON_QUERY                2020
#define IDD_DIALOG3                     2020
#define IDC_BUTTON_DOWNLOAD             2021
#define IDC_BUTTON_CANCEL               2022
#define IDD_DIALOG_DETAIL               2022
#define IDC_EDIT_MAPCODE                2023
#define IDD_DIALOG_SELECT               2023
#define IDC_BUTTON_ALTER                2023
#define IDC_EDIT2                       2024
#define IDC_EDIT_PASSWORD               2024
#define IDC_EDIT_CODE2                  2024
#define IDC_BUTTON_CHOOSEPRODUCT        2025
#define IDD_DIALOG_PRODUCTSAVE          2025
#define IDC_TREE_ASMMODEL               2026
#define IDC_BUTTON_UPLOAD               2027
#define IDD_DIALOG_BASICINFO            2028
#define IDC_EDIT3                       2029
#define IDD_DIALOG_PRODUCTDEL           2029
#define IDC_EDIT_CODE                   2029
#define IDC_CHECK1                      2030
#define IDD_DIALOG_UPDATA               2030
#define IDC_EDIT_SOLIDPLACE             2030
#define IDC_CHECK_AUDIT                 2030
#define IDC_LIST_UPLOAD                 2031
#define IDD_DIALOG_PRTNEW               2031
#define IDD_DIALOG4                     2032
#define IDD_DIALOG_NEWALTER             2032
#define IDD_DIALOG_PRTSAVEAS            2033
#define IDD_DIALOG_PRTINFO              2034
#define IDC_LIST_PRODUCT                2035
#define IDD_DIALOG_PRTMODIFY            2035
#define IDC_TREE_PRODUCT                2036
#define IDD_DIALOG_DOWNLOAD             2036
#define IDC_EDIT_MODELNAME              2037
#define IDD_DIALOG_PDTNEW               2037
#define IDC_BUTTON_MODELQUERY           2038
#define IDD_DIALOG_PDTALTER             2038
#define IDC_BUTTON_MODELDOWN            2039
#define IDD_DIALOG_PTDMODIMY            2039
#define IDD_DIALOG_PDTSAVEAS            2040
#define IDC_LIST_MODEL                  2041
#define IDC_EDIT_MODELCODE              2042
#define IDC_EDIT_MODELDESIGN            2043
#define IDI_ICON1                       2043
#define IDI_ICON2                       2044
#define IDC_BUTTON_VERIFY               2045
#define IDC_EDIT_DIMNAME                2046
#define IDD_DIALOG_PRTNDAUDIT           2047
#define IDC_EDIT5                       2048
#define IDC_EDIT_DESIGNER               2048
#define IDC_EDIT_STYLENOTE              2048
#define IDC_EDIT_GRPFRM                 2048
#define IDI_PRT                         2048
#define IDI_ICON4                       2049
#define IDC_BUTTON_OPEN                 2050
#define IDC_BUTTON_REPLACE              2051
#define IDC_LIST_PART                   2053
#define IDC_EDIT_DIMVALUE               2054
#define IDD_DIALOG_INTEGRATE            2056
#define IDD_DIALOG_ADDTOPDM             2057
#define IDD_DIALOG_PROJ                 2058
#define IDC_BUTTON_CLOSE                2059
#define IDD_DIALOG1                     2059
#define IDD_PRT_SERIES                  2060
#define IDD_NOPASS                      2061
#define IDD_DIALOG_MATERIAL             2062
#define IDD_DIALOG_PREVIEW              2063
#define IDR_MENU_RIGHTADD               2065
#define ID_PREVIEW_3D                   2066
#define IDC_STATIC_NAME                 2067
#define ID_PREVIEW_2D                   2067
#define IDD_DIALOG_PROGRESS             2069
#define IDC_LIST_GROUPDIMEN             2074
#define IDC_BUTTON_SELECT               2075
#define IDC_TREE_PARTMODEL              2076
#define IDC_STATIC_PIC                  2077
#define IDC_TREE1                       2078
#define IDC_EDIT_STYLENAME              2079
#define IDC_BUTTON_SELPRO               2080
#define IDC_EDIT_BRIEFNAME              2081
#define IDC_BUTTON_CREATE               2082
#define IDC_COMBO_STYLE                 2084
#define IDC_EDIT_MANAGER                2085
#define IDC_EDIT_UPMANAGER              2086
#define IDC_BUTTON_SELECTSTYLE          2087
#define IDC_BUTTON_SELSTAND             2089
#define IDC_EDIT_STANDNOTE              2090
#define IDC_EDIT_PRODUCTNAME            2094
#define IDC_EDIT_STYLE                  2095
#define IDC_EDIT_STAND                  2096
#define IDC_EDIT_STYLENUM               2097
#define IDC_EDIT_STYLECODE              2098
#define IDC_TREE_STYLESTAND             2099
#define IDC_EDIT_PRODUCTNOTE            2100
#define IDC_EDIT_MAP                    2102
#define IDC_BUTTON_MOTIFY               2105
#define IDC_BUTTON_MODIFY               2106
#define IDC_EDIT_PARTMAP                2107
#define IDC_EDIT_TYPE                   2108
#define IDC_EDIT_NOTE                   2109
#define IDC_LIST_PERFORMNACE            2110
#define IDC_EDIT_PARTNUM                2111
#define IDC_EDIT_PARTNAME               2112
#define IDC_BUTTON_TEST                 2113
#define IDC_COMBO_OPENTYPE              2114
#define IDC_TREE_MODEL                  2115
#define IDC_LIST_INS                    2116
#define IDC_LIST_DISPLAY                2118
#define IDC_BUTTON3                     2122
#define IDC_LIST_GROUPDIM               2125
#define IDC_BUTTON4                     2126
#define IDC_BUTTON_GRPFRM               2126
#define IDC_LIST_DIM                    2127
#define IDC_BUTTON_GRPFRM2              2127
#define IDC_BUTTON_OTHER                2128
#define IDC_BUTTON_GRPFRM3              2130
#define IDC_BUTTON_GRPFRM4              2131
#define IDC_EDIT_INSNAME                2138
#define IDC_LIST_INSPER                 2139
#define IDC_BUTTON_ADD                  2140
#define IDC_COMBO_ADDTYPE               2141
#define IDC_EDIT_PERF                   2142
#define IDC_COMBO1                      2143
#define IDC_COMBO_PERF                  2143
#define IDC_COMBO_SAVESTYLE             2143
#define IDC_COMBO_FINISH                2143
#define IDC_COMBO_KEY                   2143
#define IDC_COMBO_STATE                 2143
#define IDC_TREE_MODELGROUP             2144
#define IDC_CHECK_ALL                   2145
#define IDC_TREE_PART                   2151
#define IDC_LIST_PRODUCT_MODEL          2154
#define IDC_TREE_PRODUCT_GROUP          2155
#define IDC_BUTTON1                     2156
#define IDC_NOPASS_DETAIL               2157
#define IDC_BUTTON_SAVE                 2158
#define IDC_BUTTON8                     2158
#define IDC_NOPASS_NO                   2158
#define IDC_EDIT_PRODUCTMAP             2159
#define IDC_EDIT_ASMNUM                 2160
#define IDC_LIST_PER                    2161
#define IDC_COMBO_PARTTYPE              2162
#define IDC_EDIT_MATERIAL               2163
#define IDC_LIST_PARAMETER              2167
#define IDC_EDIT_1                      2169
#define IDC_LIST_PERFORMANCE            2170
#define IDC_LIST_INFOFINISH             2171
#define IDC_TREE_ASM                    2172
#define IDC_LIST_FINISH                 2175
#define IDC_LIST_WORKSPACE              2176
#define IDC_BUTTON_INS                  2177
#define IDC_LIST_WORKSPACE2             2177
#define IDC_BUTTON2                     2178
#define IDC_BUTTON_NEXT                 2178
#define IDC_BUTTON_SELPRT               2178
#define IDC_BUTTON_DWGSERVERPLACE       2178
#define IDC_BUTTON_FALSE                2178
#define IDC_BUTTON_PRE                  2179
#define IDC_BUTTON_SEL                  2180
#define IDC_EDIT_FILENAME               2182
#define IDC_EDIT_MDLFRM                 2184
#define IDC_EDIT_UNIT                   2185
#define IDC_BUTTON5                     2186
#define IDC_BUTTON6                     2187
#define IDC_DESIGNER                    2188
#define IDC_BUTTON_MDL                  2189
#define IDC_BUTTON9                     2189
#define IDC_BUTTON7                     2190
#define IDC_EDIT_PLACE                  2191
#define IDC_EDIT_DRWNAME                2192
#define IDC_EDIT_PLACE2                 2193
#define IDC_EDIT_DRWPLACE               2193
#define IDC_BUTTON_DRWLOCALPLACE        2194
#define IDC_BUTTON_SOLIDLOCALPLACE      2195
#define IDC_BUTTON_SOLIDSERVERPLACE     2196
#define IDC_EDIT1                       2196
#define IDC_EDIT_AUDITOR                2196
#define IDC_EDIT_INSCODE                2196
#define IDC_EDIT_VDSCODE                2196
#define IDC_EDIT_PDMCode                2196
#define IDC_Value                       2196
#define IDC_BUTTON_DRWPLACE             2197
#define IDC_EDIT_OLDSOLIDNAME           2197
#define IDC_RADIO_WORKAPACE             2199
#define IDC_RADIO_PDM                   2200
#define IDC_EDIT_KEY                    2201
#define IDC_BUTTON_SOLIDPLACE           2202
#define IDC_EDIT_OLDDRWNAME             2203
#define IDC_EDIT_SOLIDNAME1             2204
#define IDC_BUTTON_NO                   2205
#define IDC_BUTTON_PTDMDL               2206
#define IDC_EDIT_SOLIDNAME              2207
#define IDC_BUTTON_MATERIAL             2208
#define IDC_BUTTON_UNIT                 2209
#define IDC_EDIT_OLDNAME                2210
#define IDC_BUTTON_de                   2210
#define IDC_RADIO_PART                  2211
#define IDC_RADIO_ASM                   2212
#define IDC_EDIT_SOLID                  2216
#define IDC_BUTTON_SOLIDLOCAL           2219
#define IDC_BUTTON_SOLIDSERVER          2220
#define IDC_BUTTON_DRWLOCAL             2221
#define IDC_BUTTON_DRWSERVER            2222
#define IDC_BUTTON_PDTINFO              2222
#define IDC_TAB1                        2223
#define IDC_LIST3                       2228
#define IDC_LIST_VDS                    2228
#define IDC_LIST_STANDARD               2228
#define IDC_BUTTON_LOOK                 2229
#define IDC_BUTTON_                     2230
#define IDC_BUTTON_PAR                  2230
#define IDC_BUTTON_OUT                  2231
#define IDC_LIST2                       2232
#define IDC_LIST_PRODETAIL              2232
#define IDC_EDIT_USER                   2233
#define IDC_BUTTON_FINISH               2236
#define IDC_QuerySeries                 2237
#define IDC_BUTTON_REJECT               2237
#define IDC_BtnQuit                     2238
#define IDC_BUTTON_REJECT2              2238
#define IDC_BUTTON_ACCEPT               2238
#define IDC_NOPASS_YES                  2239
#define IDC_RePiPei                     2240
#define IDC_Text                        2241
#define IDC_AUTOVUEXCTRL1               2242
#define IDC_PROGRESS1                   2244
#define IDC_LABEL                       2245
#define IDC_MY_NOTE                     8015
#define IDD_DIALOG_DIM_LABEL            8021
#define IDC_MY_BUTTON_2DCREATE          8034
#define IDC_MY_BUTTON_TABELCELL         8035
#define IDC_MY_BUTTON_DESIGNATE         8037
#define IDC_MY_BUTTON_IMPORTFROMTABLE   8038
#define IDC_MY_UP_DIM_LABEL             8056
#define IDC_MY_EDIT_UP_DIM_LABEL        8057
#define IDD_DIALOG_2DDRAW               8061
#define IDD_PRT_DETAIL                  8062
#define IDD_DIALOG_UNIT                 8063
#define IDD_DIALOG_USERNAME             8064
#define IDC_MY_EDIT_NAME                8133
#define IDC_MY_THELABEL                 8134
#define IDC_MY_TREE_PARAM               8135
#define IDC_MY_LIST_PARAME              8136
#define IDC_MY_BUTTON_LOAD              8137
#define IDC_MY_BUTTON_UPDATE            8138
#define IDC_MY_COMBO1                   8139
#define IDC_MY_EXPORT                   8140

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2070
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2246
#define _APS_NEXT_SYMED_VALUE           2015
#endif
#endif
